### ISSUE TITLE
Refactor ALFATClust as a package

### ISSUE THREAD

**Issue by boneta** [phglab/ALFATClust#4]
Hi!

We really like the ALFATClust software. We want to incorporate it in our lab workflow and python scripts. Unfortunately, for the moment, the only reasonable way to do so is via external calls with `subprocess`.

It would be nice to be able to *import* ALFATClust as a package and use it integrated. I also think this could give even more flexibility to the original code, extracting intermediate information or just providing a direct pipe to other routines later. It could also mean reaching a more widespread community.

Of course, its original functionality could be keep intact.

I hope this option is considered. I would be glad to provide any help needed.

Thks!

**Comment by jimmykhchiu** [comment]
Hi @boneta,

Thanks for using our tool. While we understand that it would be more handy to import the tool in the Python codes via packages/libraries, after some discussion we decided not to implement ALFATClust as a package. Our consideration is mainly because of our own work schedule and research priorities. Nevertheless, the GPL v3 license allows users to do so,  and we welcome others to go ahead as long as they feel it worthy. Having that said, we still maintain the codes for bug fixes. Again thank you for your suggestions.
